// GENERATED by scripts/build_banners.js — do not edit.
// Run `npm run banners` after changing the source images in ads/assets.
export type Banner = {
  id: string; alt: string; width: number; height: number;
  files: Record<string, string>;
};
// Keyed by language: the Hindi reader sees the hi_ set, the English reader the en_ set.
export const BANNERS: Record<"hi" | "en", Banner[]> = {
  "hi": [
    {
      "id": "hi-man-holding-smartphone-website",
      "alt": "astropothi — Man holding smartphone website b",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/hi-man-holding-smartphone-website-800.webp",
        "1376": "/banners/hi-man-holding-smartphone-website-1376.webp"
      }
    },
    {
      "id": "hi-person-interacting-with-astrolog",
      "alt": "astropothi — Person interacting with astrolog",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/hi-person-interacting-with-astrolog-800.webp",
        "1376": "/banners/hi-person-interacting-with-astrolog-1376.webp"
      }
    },
    {
      "id": "hi-woman-reading-digital-astrology",
      "alt": "astropothi — Woman reading digital astrology",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/hi-woman-reading-digital-astrology-800.webp",
        "1376": "/banners/hi-woman-reading-digital-astrology-1376.webp"
      }
    }
  ],
  "en": [
    {
      "id": "en-man-holding-smartphone-viewing",
      "alt": "astropothi — Man holding smartphone viewing r",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/en-man-holding-smartphone-viewing-800.webp",
        "1376": "/banners/en-man-holding-smartphone-viewing-1376.webp"
      }
    },
    {
      "id": "en-man-holding-smartphone-website",
      "alt": "astropothi — Man holding smartphone website b",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/en-man-holding-smartphone-website-800.webp",
        "1376": "/banners/en-man-holding-smartphone-website-1376.webp"
      }
    },
    {
      "id": "en-person-interacting-with-digital",
      "alt": "astropothi — Person interacting with digital",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/en-person-interacting-with-digital-800.webp",
        "1376": "/banners/en-person-interacting-with-digital-1376.webp"
      }
    },
    {
      "id": "en-woman-reading-digital-report",
      "alt": "astropothi — Woman reading digital report",
      "width": 1376,
      "height": 768,
      "files": {
        "800": "/banners/en-woman-reading-digital-report-800.webp",
        "1376": "/banners/en-woman-reading-digital-report-1376.webp"
      }
    }
  ]
};
