// GENERATED by scripts/build_video.js — do not edit. Run `npm run video`.
export const PITCH_VIDEO = {
  mp4: "/video/pitch.mp4",
  webm: "/video/pitch.webm",
  poster: "/video/pitch-poster.jpg",
  width: 720,
  height: 1280,
  seconds: 10
};
