// Static UI labels used by the kundli PDF renderer.
//
// The renderer is mostly English-first; AI narrative gets generated in the
// requested language via the Bedrock prompt, but every hardcoded
// header/caption/table-cell label needs a separate translation table.
//
// Lookup pattern: `t("PLANET", lang)` returns the translated string, or the
// English fallback if the key is missing for that language.

// ──────────────────────────────────────────────────────────────────────────────
// English (source of truth — every key MUST exist here)
// ──────────────────────────────────────────────────────────────────────────────
const EN = {
  // Page titles (kept in sync with page-map.ts)
  "PAGE_COSMIC_IDENTITY":          "Cosmic Identity",
  "PAGE_COSMIC_IDENTITY_SUBTITLE": "Premium Vedic Birth Report",
  "PAGE_BASIC_DETAILS":            "Basic Astrological Details",
  "PAGE_PLANETARY_POSITIONS":      "Planetary Positions",
  "PAGE_HOROSCOPE_CHARTS":         "Horoscope Charts",
  "PAGE_DIVISIONAL_CHARTS":        "Divisional Charts",
  "PAGE_HOUSE_CUSPS":              "House Cusps and Sandhi",
  "PAGE_VIMSHOTTARI_DASHA":        "Vimshottari Dasha",
  "PAGE_FAVOURABLE_POINTS":        "Favourable Points",
  "PAGE_NUMEROLOGY_REPORT":        "Numerology Report",
  "PAGE_GAYATRI_MANTRA":           "Favourable Gayatri Mantra For You",
  "PAGE_KALSARPA_DOSHA":           "Kalsarpa Dosha",
  "PAGE_KALSARPA_DOSHA_EFFECT":    "Kalsarpa Dosha Effect",
  "PAGE_MANGLIK_ANALYSIS":         "Manglik Analysis",
  "PAGE_SADHESATI_ANALYSIS":       "Sadhesati Analysis",
  "PAGE_DOSHA_SUMMARY":            "Dosha Summary",
  "PAGE_ASHTAKAVARGA":             "Ashtakavarga",
  "PAGE_GEMSTONE_SUGGESTIONS":     "Gemstone Suggestions",
  "PAGE_LIFE_STONE":               "Life Stone",
  "PAGE_BENEFIC_STONE":            "Benefic Stone",
  "PAGE_LUCKY_STONE":              "Lucky Stone",
  "PAGE_ASCENDANT_REPORT":         "Ascendant Report",
  "PAGE_ASCENDANT_DETAILED":       "Ascendant Detailed",
  "PAGE_FINAL":                    "Thank You",

  // Cover & footer
  "COVER_HOROSCOPE_FOR":           "HOROSCOPE FOR",
  "COVER_GENERATED_BY":            "generated by",
  "FOOTER_DISCLAIMER":             "For spiritual guidance and entertainment only. See full disclaimer on the final page.",

  // Group headers
  "GROUP_BASIC_DETAILS":           "Basic Details",
  "GROUP_GHAT_CHAKRA":             "Ghat Chakra",
  "GROUP_PANCHANG_DETAILS":        "Panchang Details",
  "GROUP_ASTROLOGICAL_DETAILS":    "Astrological Details",
  "GROUP_CURRENT_DASHA":           "Current Undergoing Dasha",
  "GROUP_ABOUT_YOU":               "About You",
  "GROUP_FAVOURABLE_TIME":         "Favourable Time For You",
  "GROUP_KALSARPA_PRESENCE":       "Presence of Kalsarpa Yoga in Your Horoscope",
  "GROUP_SADHESATI_PRESENCE":      "Presence Of Sadhesati In Your Horoscope",
  "GROUP_DOSHA_OVERVIEW":          "Complete Dosha Overview",
  "GROUP_DETAILED_OBSERVATIONS":   "Detailed Observations",
  "GROUP_BHINNASHTAKAVARGA":       "Bhinnashtakavarga — Bindus by Sign",
  "GROUP_SARVASHTAKAVARGA":        "Sarvashtakavarga — House Strength",
  "GROUP_POSITIVE_TRAITS":         "Positive Traits",
  "GROUP_NEGATIVE_TRAITS":         "Negative Traits",

  // KV table labels (basic details)
  "KV_DATE_OF_BIRTH":              "Date of birth",
  "KV_TIME_OF_BIRTH":              "Time of birth",
  "KV_PLACE_OF_BIRTH":             "Place of birth",
  "KV_LATITUDE":                   "Latitude",
  "KV_LONGITUDE":                  "Longitude",
  "KV_TIMEZONE":                   "Timezone",
  "KV_AYANAMSHA":                  "Ayanamsha",
  "KV_SUNRISE":                    "Sunrise",
  "KV_SUNSET":                     "Sunset",

  // KV labels (ghat chakra / panchang)
  "KV_MONTH":                      "Month",
  "KV_TITHI":                      "Tithi",
  "KV_DAY":                        "Day",
  "KV_NAKSHATRA":                  "Nakshatra",
  "KV_YOG":                        "Yog",
  "KV_KARAN":                      "Karan",
  "KV_PRAHAR":                     "Prahar",
  "KV_MOON":                       "Moon",

  // KV labels (astrological)
  "KV_VARNA":                      "Varna",
  "KV_VASHYA":                     "Vashya",
  "KV_YONI":                       "Yoni",
  "KV_GAN":                        "Gan",
  "KV_NADI":                       "Nadi",
  "KV_SIGN":                       "Sign",
  "KV_SIGN_LORD":                  "Sign Lord",
  "KV_NAKSHATRA_LORD":             "Nakshatra Lord",
  "KV_CHARAN":                     "Charan",
  "KV_YUNJA":                      "Yunja",
  "KV_TATVA":                      "Tatva",
  "KV_NAME_ALPHABET":              "Name Alphabet",
  "KV_PAYA":                       "Paya",
  "KV_ASCENDANT":                  "Ascendant",
  "KV_ASCENDANT_LORD":             "Ascendant Lord",

  // KV labels (numerology)
  "KV_YOUR_NAME":                  "Your Name",
  "KV_RADICAL_NUMBER":             "Radical Number",
  "KV_RADICAL_RULER":              "Radical Ruler",
  "KV_FRIENDLY_NUMBERS":           "Friendly Numbers",
  "KV_NEUTRAL_NUMBERS":            "Neutral Numbers",
  "KV_EVIL_NUMBERS":               "Evil Numbers",
  "KV_FAVOURABLE_DAYS":            "Favourable Days",
  "KV_FAVOURABLE_STONE":           "Favourable Stone",
  "KV_FAVOURABLE_SUB_STONE":       "Favourable Sub Stone",
  "KV_FAVOURABLE_GOD":             "Favourable God",
  "KV_FAVOURABLE_METAL":           "Favourable Metal",
  "KV_FAVOURABLE_COLOR":           "Favourable Color",
  "KV_FAVOURABLE_MANTRA":          "Favourable Mantra",

  // KV labels (sadhesati panel)
  "KV_CONSIDERATION_DATE":         "Consideration Date",
  "KV_SATURN_SIGN":                "Saturn Sign",
  "KV_MOON_SIGN":                  "Moon Sign",
  "KV_SATURN_RETROGRADE":          "Saturn retrograde",

  // KV labels (gemstones)
  "KV_SUBSTITUTES":                "Substitutes",
  "KV_FINGER":                     "Finger",
  "KV_WEIGHT":                     "Weight",
  "KV_DEITY":                      "Deity",
  "KV_METAL":                      "Metal",

  // KV labels (ascendant)
  "KV_LORD":                       "Lord",
  "KV_SYMBOL":                     "Symbol",
  "KV_CHARACTERISTICS":            "Characteristics",
  "KV_LUCKY_GEMS":                 "Lucky gems",
  "KV_DAY_OF_FAST":                "Day of fast",

  // Big-number block labels (numerology)
  "LBL_DESTINY_NUMBER":            "Destiny Number",
  "LBL_RADICAL_NUMBER":            "Radical Number",
  "LBL_NAME_NUMBER":               "Name Number",

  // Table column headers (planetary positions)
  "COL_PLANETS":                   "Planets",
  "COL_R":                         "R",  // retrograde flag
  "COL_SIGN":                      "Sign",
  "COL_DEGREES":                   "Degrees",
  "COL_SIGN_LORD":                 "Sign Lord",
  "COL_NAKSHATRA":                 "Nakshatra",
  "COL_NAKSHATRA_LORD":            "Nakshatra Lord",
  "COL_HOUSE":                     "House",
  "COL_BHAV_MADHYA":               "Bhav Madhya",
  "COL_BHAV_SANDHI":               "Bhav Sandhi",
  "COL_DASHA_NAME":                "Dasha Name",
  "COL_START_DATE":                "Start Date",
  "COL_END_DATE":                  "End Date",
  "COL_BINDUS":                    "Bindus",
  "COL_STRENGTH":                  "Strength",
  "COL_PLANET":                    "Planet",
  "COL_TOTAL":                     "Total",
  "VAL_YES_RETRO":                 "Yes",  // retrograde yes
  "VAL_NO_RETRO":                  "--",   // retrograde no

  // Strength verdicts (ashtakavarga)
  "STRENGTH_EXCELLENT":            "Excellent",
  "STRENGTH_GOOD":                 "Good",
  "STRENGTH_AVERAGE":              "Average",
  "STRENGTH_WEAK":                 "Weak",

  // Planet intensity (rendered on the 9 planet cards on page 3)
  "INTENSITY_HIGHLY_FAVORABLE":    "Highly Favorable",
  "INTENSITY_FAVORABLE":           "Favorable",
  "INTENSITY_NEUTRAL":             "Neutral",
  "INTENSITY_UNFAVORABLE":         "Unfavorable",

  // Chart titles
  "CHART_LAGNA_BIRTH":             "Lagna Chart (Birth Chart)",
  "CHART_MOON":                    "Moon Chart",
  "CHART_NAVAMSHA_D9":             "Navamsha Chart (D9)",
  "CHART_CHALIT":                  "Chalit Chart",

  // Divisional chart titles + descriptions (5-grid on page 5)
  "DCHART_SUN":           "Sun Chart",
  "DCHART_HORA":          "Hora Chart (D2)",
  "DCHART_DRESHKAN":      "Dreshkan Chart (D3)",
  "DCHART_CHATHURTH":     "Chathurthamasha (D4)",
  "DCHART_PANCH":         "Panchmansha (D5)",
  "DCHART_SAPT":          "Saptamansha (D7)",
  "DCHART_ASHT":          "Ashtamansha (D8)",
  "DCHART_DASH":          "Dashamansha (D10)",
  "DCHART_DWAD":          "Dwadasha (D12)",
  "DCHART_DESC_SUN":      "Health, Constitution, Body",
  "DCHART_DESC_HORA":     "Finance, Wealth, Prosperity",
  "DCHART_DESC_DRESHKAN": "Brothers, Sisters",
  "DCHART_DESC_CHATHURTH":"Fortunes, Luck of native",
  "DCHART_DESC_PANCH":    "Shows Spiritualism",
  "DCHART_DESC_SAPT":     "Impregnation, Birth of the child",
  "DCHART_DESC_ASHT":     "Shows Longevity",
  "DCHART_DESC_DASH":     "Livelihood, Profession",
  "DCHART_DESC_DWAD":     "Parents, Paternal happiness",

  // Dasha labels (current undergoing)
  "DASHA_MAHA":                    "MAHADASHA",
  "DASHA_ANTAR":                   "ANTARDASHA",
  "DASHA_PRTYANTAR":               "PRTYANTAR DASHA",
  "DASHA_NOTE":                    "* NOTE : All the dates are indicating dasha end date.",

  // Kalsarpa panel
  "KALSARPA_PRESENT":              "Kalsarpa is present",
  "KALSARPA_NOT_PRESENT":          "Kalsarpa not present",
  "KALSARPA_NAME_LABEL":           "Kalsarpa Name",
  "KALSARPA_DIRECTION_LABEL":      "Direction",
  "KALSARPA_FULL_DESCENDING":      "FULL DESCENDING",
  "KALSARPA_NOT_FORMED":           "NOT FORMED",
  "KALSARPA_NONE":                 "NONE",
  "KALSARPA_REPORT_TITLE":         "Kaal Sarp Dosh Report",
  "KALSARPA_REMEDIES_TITLE":       "Remedies Of Kaal Sarp Dosh",

  // Manglik panel
  "MANGLIK_WHAT_IS":               "What is manglik dosha?",
  "MANGLIK_ANALYSIS_TITLE":        "Manglik Analysis",
  "MANGLIK_TOTAL_PCT":             "TOTAL MANGLIK PERCENTAGE",
  "MANGLIK_REPORT_TITLE":          "Manglik Report",
  "MANGLIK_BASED_ON_HOUSE":        "Based On House",
  "MANGLIK_BASED_ON_ASPECTS":      "Based On Aspects",
  "MANGLIK_REMEDIES_TITLE":        "Remedies Of Manglik Dosha",

  // Sadhesati
  "SADHESATI_WHAT_IS":             "What is Sadhesati dosha?",
  "SADHESATI_PRESENT":             "Sadhesati Dosha is Present",
  "SADHESATI_NOT_PRESENT":         "Sadhesati Dosha is Not Present",
  "SADHESATI_YES_NOTE":            "Yes, currently you are undergoing Sadhesati.",
  "SADHESATI_NO_NOTE":             "You are not currently in Sadhesati.",

  // Dosha summary card states
  "DOSHA_NOT_FOUND":               "Not Found",
  "DOSHA_PRESENT_PREFIX":          "Present",  // followed by " · {severity}"

  // Ashtakavarga
  "ASHTAKAVARGA_TOTAL":            "SARVASHTAKAVARGA TOTAL",
  "ASHTAKAVARGA_SAV":              "SAV",

  // Gemstone cards
  "GEM_LIFE_STONE":                "LIFE STONE",
  "GEM_BENEFIC_STONE":             "BENEFIC STONE",
  "GEM_LUCKY_STONE":               "LUCKY STONE",
  "GEM_LIFE_STONE_TITLE":          "LIFE STONE",
  "GEM_BENEFIC_STONE_TITLE":       "BENEFIC STONE",
  "GEM_LUCKY_STONE_TITLE":         "LUCKY STONE",
  "GEM_CELL_DESCRIPTION":          "Description",
  "GEM_CELL_TIME_TO_WEAR":         "Time to wear",
  "GEM_CELL_FINGER":               "Finger",
  "GEM_CELL_WEIGHT_AND_METAL":     "Weight and metal",
  "GEM_CELL_MANTRA":               "Mantra",
  "GEM_CELL_SUBSTITUTES":          "Substitutes",
  "GEM_CELL_RITUALS":              "Energizing Rituals",
  "GEM_CELL_CAUTION":              "Caution",

  // Ascendant detailed (page 24)
  "ASCENDANT_SPIRITUAL_LESSON":    "Spiritual lesson to learn",

  // Final page
  "FINAL_DISCLAIMER_TITLE":        "DISCLAIMER",
  "SUPPORT_TITLE":                 "Need help with this report?",
  "SUPPORT_BODY":                  "Write to us and a person will read it. We answer questions about your chart, your reading, or your order.",
  "SUPPORT_WHATSAPP":              "WhatsApp",
  "SUPPORT_EMAIL":                 "Email",
  "FINAL_DISCLAIMER_BODY":
    "This report is generated using classical Vedic astrology principles (Lahiri Ayanamsha, Whole-Sign houses) "
    + "and is provided for spiritual guidance and entertainment purposes only. Accuracy depends on the exactness of the "
    + "birth time provided. Astrological interpretations and suggested remedies are traditional references and must not "
    + "be treated as medical, psychological, legal, financial, or professional advice of any kind. No decision involving "
    + "health, relationships, career, investments, or legal matters should be made solely on the basis of this report. "
    + "The author and publisher accept no liability for any direct or consequential loss arising from use of this material. "
    + "Different ayanamsha conventions and house systems may produce variations from reports prepared elsewhere.",

  // Short helper strings
  "WORD_HOUSE":                    "House",   // used like "House 7"
  "WORD_PRESENT":                  "Present",

  // ── Dosha PDF labels ───────────────────────────────────────────────────
  "DOSHA_FOOTER_TAG":              "For spiritual guidance and reflection. Uses Lahiri Ayanamsha with Whole-Sign houses.",
  "DOSHA_REPORT_BANNER":           "PERSONALISED  DOSHA  REPORT",
  "DOSHA_KICKER_OVERVIEW":         "Overview",
  "DOSHA_KICKER_DETAIL":           "Dosha Detail",
  "DOSHA_KICKER_NARRATIVE":        "Narrative",
  "DOSHA_KICKER_CLOSING":          "Closing",
  "DOSHA_PAGE_SUMMARY":            "Dosha Summary",

  "DOSHA_STAT_ACTIVE":             "Active",
  "DOSHA_STAT_SEVERE":             "Severe",
  "DOSHA_STAT_HIGH":               "High",
  "DOSHA_STAT_MODERATE":           "Moderate",
  "DOSHA_STAT_MILD":               "Mild",
  "DOSHA_STAT_CHECKED":            "Checked",

  "DOSHA_LBL_SUBJECT":             "SUBJECT",
  "DOSHA_LBL_BORN":                "Born",
  "DOSHA_LBL_PLACE":               "Place",
  "DOSHA_LBL_MOON":                "Moon",
  "DOSHA_LBL_NAKSHATRA":           "Nakshatra",
  "DOSHA_LBL_ASCENDANT":           "Ascendant",
  "DOSHA_FLAGGED_HEADER":          "Flagged in this chart",
  "DOSHA_CLEAR_HEADER":            "Checked and clear",
  "DOSHA_CLEAR_TITLE":             "Clear chart — no doshas detected",
  "DOSHA_CLEAR_BODY":              "All five major doshas are absent.",

  "DOSHA_PAGE_PREFIX":             "Page",
  "DOSHA_PAGE_SUMMARY_LABEL":      "Page 2 — Summary",
  "DOSHA_RULER_PREFIX":            "Ruler —",

  "DOSHA_SEC_ABOUT":               "About this dosha",
  "DOSHA_SEC_REASON":              "Why it applies in your chart",
  "DOSHA_SEC_MEANS":               "What this means for you",
  "DOSHA_SEC_SADESATI":            "Sade Sati timeline",
  "DOSHA_SEC_CANCELLATIONS":       "Classical cancellations & mitigators",
  "DOSHA_SEC_EFFECTS":             "Effects to watch",
  "DOSHA_SEC_REMEDIES":            "Remedies",
  "DOSHA_SEC_REMEDY":              "Remedy",
  "DOSHA_SEC_LUCKY":               "Lucky values for the antidote",

  "DOSHA_WINDOW":                  "Window",
  "DOSHA_COMPLETE":                "complete",
  "DOSHA_SATURN_IN":               "Saturn in",

  "DOSHA_VERDICT_NONE":            "No dosha",
  "DOSHA_VERDICT_CANCELLED":       "Fully cancelled",
  "DOSHA_VERDICT_REDUCED":         "Substantially reduced",
  "DOSHA_VERDICT_PARTIAL":         "Partially reduced",
  "DOSHA_VERDICT_ACTIVE":          "Full strength",

  "DOSHA_WEIGHT_FULL":             "FULL",
  "DOSHA_WEIGHT_PARTIAL":          "PARTIAL",
  "DOSHA_WEIGHT_NOTE":             "NOTE",

  "DOSHA_LUCKY_COLOR":             "Color",
  "DOSHA_LUCKY_DAY":               "Day",
  "DOSHA_LUCKY_NUMBER":            "Number",
  "DOSHA_LUCKY_GEMSTONE":          "Gemstone",
  "DOSHA_LUCKY_METAL":             "Metal",
  "DOSHA_LUCKY_DIRECTION":         "Direction",
  "DOSHA_LUCKY_DEITY":             "Deity",
  "DOSHA_LUCKY_MANTRA":            "Mantra",

  "DOSHA_AI_TITLE":                "Personalised AI Reading",
  "DOSHA_AI_OVERALL":              "Overall theme",
  "DOSHA_AI_PER_DOSHA":            "Per-dosha narrative",
  "DOSHA_AI_GUIDANCE":             "Practical guidance",

  "DOSHA_CLEAR_PAGE_TITLE":        "Clear Chart",
  "DOSHA_CLEAR_NO_MAJOR":          "No major doshas detected",
  "DOSHA_CLEAR_LONG":              "Your chart is clean on Manglik, Kaal Sarp, Sade Sati, Pitra and Guru Chandal — the five doshas that most commonly affect marriage, family fortune and mental peace.",
};

// ──────────────────────────────────────────────────────────────────────────────
// Hindi
// ──────────────────────────────────────────────────────────────────────────────
const HI = {
  "PAGE_COSMIC_IDENTITY":          "ब्रह्मांडीय पहचान",
  "PAGE_COSMIC_IDENTITY_SUBTITLE": "प्रीमियम वैदिक जन्म रिपोर्ट",
  "PAGE_BASIC_DETAILS":            "मूल ज्योतिषीय विवरण",
  "PAGE_PLANETARY_POSITIONS":      "ग्रह स्थिति",
  "PAGE_HOROSCOPE_CHARTS":         "जन्म कुंडली चार्ट",
  "PAGE_DIVISIONAL_CHARTS":        "विभाजनात्मक चार्ट",
  "PAGE_HOUSE_CUSPS":              "भाव कुस्प और संधि",
  "PAGE_VIMSHOTTARI_DASHA":        "विंशोत्तरी दशा",
  "PAGE_FAVOURABLE_POINTS":        "शुभ बिंदु",
  "PAGE_NUMEROLOGY_REPORT":        "अंक ज्योतिष रिपोर्ट",
  "PAGE_GAYATRI_MANTRA":           "आपके लिए शुभ गायत्री मंत्र",
  "PAGE_KALSARPA_DOSHA":           "कालसर्प दोष",
  "PAGE_KALSARPA_DOSHA_EFFECT":    "कालसर्प दोष का प्रभाव",
  "PAGE_MANGLIK_ANALYSIS":         "मांगलिक विश्लेषण",
  "PAGE_SADHESATI_ANALYSIS":       "साढ़ेसाती विश्लेषण",
  "PAGE_DOSHA_SUMMARY":            "दोष सारांश",
  "PAGE_ASHTAKAVARGA":             "अष्टकवर्ग",
  "PAGE_GEMSTONE_SUGGESTIONS":     "रत्न सुझाव",
  "PAGE_LIFE_STONE":               "जीवन रत्न",
  "PAGE_BENEFIC_STONE":            "कारक रत्न",
  "PAGE_LUCKY_STONE":              "भाग्य रत्न",
  "PAGE_ASCENDANT_REPORT":         "लग्न रिपोर्ट",
  "PAGE_ASCENDANT_DETAILED":       "लग्न विस्तृत",
  "PAGE_FINAL":                    "धन्यवाद",

  "COVER_HOROSCOPE_FOR":           "कुंडली",
  "COVER_GENERATED_BY":            "द्वारा निर्मित",
  "FOOTER_DISCLAIMER":             "केवल आध्यात्मिक मार्गदर्शन और मनोरंजन के लिए। पूर्ण अस्वीकरण अंतिम पृष्ठ पर देखें।",

  "GROUP_BASIC_DETAILS":           "मूल विवरण",
  "GROUP_GHAT_CHAKRA":             "घात चक्र",
  "GROUP_PANCHANG_DETAILS":        "पंचांग विवरण",
  "GROUP_ASTROLOGICAL_DETAILS":    "ज्योतिषीय विवरण",
  "GROUP_CURRENT_DASHA":           "वर्तमान चल रही दशा",
  "GROUP_ABOUT_YOU":               "आपके बारे में",
  "GROUP_FAVOURABLE_TIME":         "आपके लिए शुभ समय",
  "GROUP_KALSARPA_PRESENCE":       "आपकी कुंडली में कालसर्प योग की उपस्थिति",
  "GROUP_SADHESATI_PRESENCE":      "आपकी कुंडली में साढ़ेसाती की उपस्थिति",
  "GROUP_DOSHA_OVERVIEW":          "संपूर्ण दोष विवरण",
  "GROUP_DETAILED_OBSERVATIONS":   "विस्तृत अवलोकन",
  "GROUP_BHINNASHTAKAVARGA":       "भिन्नाष्टकवर्ग — राशि के अनुसार बिंदु",
  "GROUP_SARVASHTAKAVARGA":        "सर्वाष्टकवर्ग — भाव शक्ति",
  "GROUP_POSITIVE_TRAITS":         "सकारात्मक गुण",
  "GROUP_NEGATIVE_TRAITS":         "नकारात्मक गुण",

  "KV_DATE_OF_BIRTH":              "जन्म तिथि",
  "KV_TIME_OF_BIRTH":              "जन्म समय",
  "KV_PLACE_OF_BIRTH":             "जन्म स्थान",
  "KV_LATITUDE":                   "अक्षांश",
  "KV_LONGITUDE":                  "देशांतर",
  "KV_TIMEZONE":                   "समय क्षेत्र",
  "KV_AYANAMSHA":                  "अयनांश",
  "KV_SUNRISE":                    "सूर्योदय",
  "KV_SUNSET":                     "सूर्यास्त",

  "KV_MONTH":                      "मास",
  "KV_TITHI":                      "तिथि",
  "KV_DAY":                        "वार",
  "KV_NAKSHATRA":                  "नक्षत्र",
  "KV_YOG":                        "योग",
  "KV_KARAN":                      "करण",
  "KV_PRAHAR":                     "प्रहर",
  "KV_MOON":                       "चंद्र",

  "KV_VARNA":                      "वर्ण",
  "KV_VASHYA":                     "वश्य",
  "KV_YONI":                       "योनि",
  "KV_GAN":                        "गण",
  "KV_NADI":                       "नाड़ी",
  "KV_SIGN":                       "राशि",
  "KV_SIGN_LORD":                  "राशि स्वामी",
  "KV_NAKSHATRA_LORD":             "नक्षत्र स्वामी",
  "KV_CHARAN":                     "चरण",
  "KV_YUNJA":                      "युंजा",
  "KV_TATVA":                      "तत्व",
  "KV_NAME_ALPHABET":              "नाम अक्षर",
  "KV_PAYA":                       "पाया",
  "KV_ASCENDANT":                  "लग्न",
  "KV_ASCENDANT_LORD":             "लग्न स्वामी",

  "KV_YOUR_NAME":                  "आपका नाम",
  "KV_RADICAL_NUMBER":             "मूलांक",
  "KV_RADICAL_RULER":              "मूलांक स्वामी",
  "KV_FRIENDLY_NUMBERS":           "मित्र अंक",
  "KV_NEUTRAL_NUMBERS":            "सम अंक",
  "KV_EVIL_NUMBERS":               "शत्रु अंक",
  "KV_FAVOURABLE_DAYS":            "शुभ दिन",
  "KV_FAVOURABLE_STONE":           "शुभ रत्न",
  "KV_FAVOURABLE_SUB_STONE":       "शुभ उप-रत्न",
  "KV_FAVOURABLE_GOD":             "शुभ देवता",
  "KV_FAVOURABLE_METAL":           "शुभ धातु",
  "KV_FAVOURABLE_COLOR":           "शुभ रंग",
  "KV_FAVOURABLE_MANTRA":          "शुभ मंत्र",

  "KV_CONSIDERATION_DATE":         "विचार तिथि",
  "KV_SATURN_SIGN":                "शनि राशि",
  "KV_MOON_SIGN":                  "चंद्र राशि",
  "KV_SATURN_RETROGRADE":          "शनि वक्री",

  "KV_SUBSTITUTES":                "उप-रत्न",
  "KV_FINGER":                     "अंगुली",
  "KV_WEIGHT":                     "वजन",
  "KV_DEITY":                      "देवता",
  "KV_METAL":                      "धातु",

  "KV_LORD":                       "स्वामी",
  "KV_SYMBOL":                     "चिन्ह",
  "KV_CHARACTERISTICS":            "विशेषताएं",
  "KV_LUCKY_GEMS":                 "शुभ रत्न",
  "KV_DAY_OF_FAST":                "व्रत का दिन",

  "LBL_DESTINY_NUMBER":            "भाग्यांक",
  "LBL_RADICAL_NUMBER":            "मूलांक",
  "LBL_NAME_NUMBER":               "नामांक",

  "COL_PLANETS":                   "ग्रह",
  "COL_R":                         "वक्री",
  "COL_SIGN":                      "राशि",
  "COL_DEGREES":                   "अंश",
  "COL_SIGN_LORD":                 "राशि स्वामी",
  "COL_NAKSHATRA":                 "नक्षत्र",
  "COL_NAKSHATRA_LORD":            "नक्षत्र स्वामी",
  "COL_HOUSE":                     "भाव",
  "COL_BHAV_MADHYA":               "भाव मध्य",
  "COL_BHAV_SANDHI":               "भाव संधि",
  "COL_DASHA_NAME":                "दशा नाम",
  "COL_START_DATE":                "आरंभ तिथि",
  "COL_END_DATE":                  "समाप्ति तिथि",
  "COL_BINDUS":                    "बिंदु",
  "COL_STRENGTH":                  "शक्ति",
  "COL_PLANET":                    "ग्रह",
  "COL_TOTAL":                     "कुल",
  "VAL_YES_RETRO":                 "हां",
  "VAL_NO_RETRO":                  "--",

  "STRENGTH_EXCELLENT":            "उत्कृष्ट",
  "STRENGTH_GOOD":                 "अच्छा",
  "STRENGTH_AVERAGE":              "औसत",
  "STRENGTH_WEAK":                 "कमज़ोर",

  // Planet intensity — match the language used in established Hindi kundli reports
  "INTENSITY_HIGHLY_FAVORABLE":    "योगकारक",
  "INTENSITY_FAVORABLE":           "लाभप्रद",
  "INTENSITY_NEUTRAL":             "सम",
  "INTENSITY_UNFAVORABLE":         "हानिप्रद",

  "CHART_LAGNA_BIRTH":             "लग्न चार्ट (जन्म चार्ट)",
  "CHART_MOON":                    "चंद्र चार्ट",
  "CHART_NAVAMSHA_D9":             "नवांश चार्ट (D9)",
  "CHART_CHALIT":                  "चलित चार्ट",

  "DCHART_SUN":           "सूर्य चार्ट",
  "DCHART_HORA":          "होरा चार्ट (D2)",
  "DCHART_DRESHKAN":      "द्रेष्काण चार्ट (D3)",
  "DCHART_CHATHURTH":     "चतुर्थांश (D4)",
  "DCHART_PANCH":         "पंचमांश (D5)",
  "DCHART_SAPT":          "सप्तमांश (D7)",
  "DCHART_ASHT":          "अष्टमांश (D8)",
  "DCHART_DASH":          "दशमांश (D10)",
  "DCHART_DWAD":          "द्वादशांश (D12)",
  "DCHART_DESC_SUN":      "स्वास्थ्य, संरचना, शरीर",
  "DCHART_DESC_HORA":     "धन, संपदा, समृद्धि",
  "DCHART_DESC_DRESHKAN": "भाई, बहन",
  "DCHART_DESC_CHATHURTH":"भाग्य, सौभाग्य",
  "DCHART_DESC_PANCH":    "आध्यात्मिकता दर्शाता है",
  "DCHART_DESC_SAPT":     "गर्भधारण, संतान का जन्म",
  "DCHART_DESC_ASHT":     "आयु दर्शाता है",
  "DCHART_DESC_DASH":     "आजीविका, व्यवसाय",
  "DCHART_DESC_DWAD":     "माता-पिता, पैतृक सुख",

  "DASHA_MAHA":                    "महादशा",
  "DASHA_ANTAR":                   "अंतर्दशा",
  "DASHA_PRTYANTAR":               "प्रत्यंतर दशा",
  "DASHA_NOTE":                    "* नोट: सभी तिथियाँ दशा की समाप्ति तिथि दर्शाती हैं।",

  "KALSARPA_PRESENT":              "कालसर्प दोष उपस्थित है",
  "KALSARPA_NOT_PRESENT":          "कालसर्प दोष नहीं है",
  "KALSARPA_NAME_LABEL":           "कालसर्प नाम",
  "KALSARPA_DIRECTION_LABEL":      "दिशा",
  "KALSARPA_FULL_DESCENDING":      "पूर्ण अवरोही",
  "KALSARPA_NOT_FORMED":           "नहीं बना",
  "KALSARPA_NONE":                 "कोई नहीं",
  "KALSARPA_REPORT_TITLE":         "कालसर्प दोष रिपोर्ट",
  "KALSARPA_REMEDIES_TITLE":       "कालसर्प दोष के उपाय",

  "MANGLIK_WHAT_IS":               "मांगलिक दोष क्या है?",
  "MANGLIK_ANALYSIS_TITLE":        "मांगलिक विश्लेषण",
  "MANGLIK_TOTAL_PCT":             "कुल मांगलिक प्रतिशत",
  "MANGLIK_REPORT_TITLE":          "मांगलिक रिपोर्ट",
  "MANGLIK_BASED_ON_HOUSE":        "भाव के आधार पर",
  "MANGLIK_BASED_ON_ASPECTS":      "दृष्टि के आधार पर",
  "MANGLIK_REMEDIES_TITLE":        "मांगलिक दोष के उपाय",

  "SADHESATI_WHAT_IS":             "साढ़ेसाती दोष क्या है?",
  "SADHESATI_PRESENT":             "साढ़ेसाती दोष उपस्थित है",
  "SADHESATI_NOT_PRESENT":         "साढ़ेसाती दोष नहीं है",
  "SADHESATI_YES_NOTE":            "हाँ, वर्तमान में आप साढ़ेसाती से गुज़र रहे हैं।",
  "SADHESATI_NO_NOTE":             "आप वर्तमान में साढ़ेसाती में नहीं हैं।",

  "DOSHA_NOT_FOUND":               "नहीं मिला",
  "DOSHA_PRESENT_PREFIX":          "उपस्थित",

  "ASHTAKAVARGA_TOTAL":            "सर्वाष्टकवर्ग कुल",
  "ASHTAKAVARGA_SAV":              "सर्व",

  "GEM_LIFE_STONE":                "जीवन रत्न",
  "GEM_BENEFIC_STONE":             "कारक रत्न",
  "GEM_LUCKY_STONE":               "भाग्य रत्न",
  "GEM_LIFE_STONE_TITLE":          "जीवन रत्न",
  "GEM_BENEFIC_STONE_TITLE":       "कारक रत्न",
  "GEM_LUCKY_STONE_TITLE":         "भाग्य रत्न",
  "GEM_CELL_DESCRIPTION":          "विवरण",
  "GEM_CELL_TIME_TO_WEAR":         "धारण का समय",
  "GEM_CELL_FINGER":               "अंगुली",
  "GEM_CELL_WEIGHT_AND_METAL":     "वजन और धातु",
  "GEM_CELL_MANTRA":               "मंत्र",
  "GEM_CELL_SUBSTITUTES":          "उप-रत्न",
  "GEM_CELL_RITUALS":              "ऊर्जा संस्कार",
  "GEM_CELL_CAUTION":              "सावधानी",

  "ASCENDANT_SPIRITUAL_LESSON":    "सीखने योग्य आध्यात्मिक पाठ",

  "FINAL_DISCLAIMER_TITLE":        "अस्वीकरण",
  "SUPPORT_TITLE":                 "इस रिपोर्ट के बारे में कोई प्रश्न है?",
  "SUPPORT_BODY":                  "हमें लिखिए — आपका संदेश एक व्यक्ति पढ़ेगा। कुंडली, रिपोर्ट या ऑर्डर से जुड़ा कोई भी प्रश्न पूछ सकते हैं।",
  "SUPPORT_WHATSAPP":              "व्हाट्सएप",
  "SUPPORT_EMAIL":                 "ईमेल",
  "FINAL_DISCLAIMER_BODY":
    "यह रिपोर्ट शास्त्रीय वैदिक ज्योतिष सिद्धांतों (लाहिड़ी अयनांश, संपूर्ण-राशि भाव) के आधार पर तैयार की गई है "
    + "और केवल आध्यात्मिक मार्गदर्शन एवं मनोरंजन के उद्देश्य से प्रदान की जा रही है। सटीकता प्रदान किए गए जन्म "
    + "समय की शुद्धता पर निर्भर करती है। ज्योतिषीय व्याख्याएँ और सुझाए गए उपाय पारंपरिक संदर्भ हैं और इन्हें "
    + "किसी भी प्रकार की चिकित्सीय, मनोवैज्ञानिक, कानूनी, वित्तीय या पेशेवर सलाह के रूप में नहीं लिया जाना चाहिए। "
    + "स्वास्थ्य, संबंध, करियर, निवेश या कानूनी मामलों से संबंधित कोई भी निर्णय केवल इस रिपोर्ट के आधार पर नहीं "
    + "लिया जाना चाहिए। इस सामग्री के उपयोग से होने वाली किसी भी प्रत्यक्ष या अप्रत्यक्ष हानि के लिए लेखक और "
    + "प्रकाशक कोई उत्तरदायित्व स्वीकार नहीं करते। विभिन्न अयनांश परंपराओं और भाव पद्धतियों से अन्यत्र तैयार की "
    + "गई रिपोर्टों में भिन्नता आ सकती है।",

  "WORD_HOUSE":                    "भाव",
  "WORD_PRESENT":                  "उपस्थित",

  // Dosha PDF labels
  "DOSHA_FOOTER_TAG":              "केवल आध्यात्मिक मार्गदर्शन और चिंतन के लिए। लाहिड़ी अयनांश और संपूर्ण-राशि भाव पद्धति का उपयोग।",
  "DOSHA_REPORT_BANNER":           "व्यक्तिगत  दोष  रिपोर्ट",
  "DOSHA_KICKER_OVERVIEW":         "अवलोकन",
  "DOSHA_KICKER_DETAIL":           "दोष विवरण",
  "DOSHA_KICKER_NARRATIVE":        "वर्णन",
  "DOSHA_KICKER_CLOSING":          "समापन",
  "DOSHA_PAGE_SUMMARY":            "दोष सारांश",

  "DOSHA_STAT_ACTIVE":             "सक्रिय",
  "DOSHA_STAT_SEVERE":             "गंभीर",
  "DOSHA_STAT_HIGH":               "प्रबल",
  "DOSHA_STAT_MODERATE":           "मध्यम",
  "DOSHA_STAT_MILD":               "हल्का",
  "DOSHA_STAT_CHECKED":            "जांचे गए",

  "DOSHA_LBL_SUBJECT":             "विषय",
  "DOSHA_LBL_BORN":                "जन्म",
  "DOSHA_LBL_PLACE":               "स्थान",
  "DOSHA_LBL_MOON":                "चंद्र",
  "DOSHA_LBL_NAKSHATRA":           "नक्षत्र",
  "DOSHA_LBL_ASCENDANT":           "लग्न",
  "DOSHA_FLAGGED_HEADER":          "इस कुंडली में पाए गए दोष",
  "DOSHA_CLEAR_HEADER":            "जाँचे गए — इनसे कुंडली मुक्त है",
  "DOSHA_CLEAR_TITLE":             "स्वच्छ कुंडली — कोई दोष नहीं मिला",
  "DOSHA_CLEAR_BODY":              "पाँचों प्रमुख दोष अनुपस्थित हैं।",

  "DOSHA_PAGE_PREFIX":             "पृष्ठ",
  "DOSHA_PAGE_SUMMARY_LABEL":      "पृष्ठ 2 — सारांश",
  "DOSHA_RULER_PREFIX":            "स्वामी —",

  "DOSHA_SEC_ABOUT":               "इस दोष के बारे में",
  "DOSHA_SEC_REASON":              "यह आपकी कुंडली पर क्यों लागू होता है",
  "DOSHA_SEC_MEANS":               "आपके लिए इसका क्या अर्थ है",
  "DOSHA_SEC_SADESATI":            "साढ़ेसाती समयरेखा",
  "DOSHA_SEC_CANCELLATIONS":       "शास्त्रीय निरस्तीकरण एवं शमक",
  "DOSHA_SEC_EFFECTS":             "ध्यान देने योग्य प्रभाव",
  "DOSHA_SEC_REMEDIES":            "उपाय",
  "DOSHA_SEC_REMEDY":              "उपाय",
  "DOSHA_SEC_LUCKY":               "उपाय के लिए शुभ मान",

  "DOSHA_WINDOW":                  "अवधि",
  "DOSHA_COMPLETE":                "पूर्ण",
  "DOSHA_SATURN_IN":               "शनि",

  "DOSHA_VERDICT_NONE":            "कोई दोष नहीं",
  "DOSHA_VERDICT_CANCELLED":       "पूर्णतः निरस्त",
  "DOSHA_VERDICT_REDUCED":         "महत्त्वपूर्ण रूप से कम",
  "DOSHA_VERDICT_PARTIAL":         "आंशिक रूप से कम",
  "DOSHA_VERDICT_ACTIVE":          "पूर्ण शक्ति",

  "DOSHA_WEIGHT_FULL":             "पूर्ण",
  "DOSHA_WEIGHT_PARTIAL":          "आंशिक",
  "DOSHA_WEIGHT_NOTE":             "टिप्पणी",

  "DOSHA_LUCKY_COLOR":             "रंग",
  "DOSHA_LUCKY_DAY":               "दिन",
  "DOSHA_LUCKY_NUMBER":            "संख्या",
  "DOSHA_LUCKY_GEMSTONE":          "रत्न",
  "DOSHA_LUCKY_METAL":             "धातु",
  "DOSHA_LUCKY_DIRECTION":         "दिशा",
  "DOSHA_LUCKY_DEITY":             "देवता",
  "DOSHA_LUCKY_MANTRA":            "मंत्र",

  "DOSHA_AI_TITLE":                "व्यक्तिगत ज्योतिषीय विश्लेषण",
  "DOSHA_AI_OVERALL":              "समग्र विश्लेषण",
  "DOSHA_AI_PER_DOSHA":            "प्रत्येक दोष का विवरण",
  "DOSHA_AI_GUIDANCE":             "व्यावहारिक मार्गदर्शन",

  "DOSHA_CLEAR_PAGE_TITLE":        "स्वच्छ कुंडली",
  "DOSHA_CLEAR_NO_MAJOR":          "कोई बड़ा दोष नहीं मिला",
  "DOSHA_CLEAR_LONG":              "आपकी कुंडली मांगलिक, कालसर्प, साढ़ेसाती, पितृ और गुरु चांडाल — इन पाँच दोषों से मुक्त है, जो विवाह, पारिवारिक सौभाग्य और मानसिक शांति को सबसे अधिक प्रभावित करते हैं।",
};

// ──────────────────────────────────────────────────────────────────────────────
// Marathi (uses Devanagari; same font registration as Hindi covers it)
// Translation coverage is intentionally light — we mirror Hindi for shared
// terms and only override where Marathi differs notably.
// ──────────────────────────────────────────────────────────────────────────────
const MR = {
  ...HI,
  "COVER_HOROSCOPE_FOR":           "कुंडली",
  "COVER_GENERATED_BY":            "द्वारा तयार",
};

const DICTS = {
  en: EN,
  hi: HI,
  mr: MR,
  gu: undefined,
  bn: undefined,
  ta: undefined,
  te: undefined,
  kn: undefined,
  ml: undefined,
  pa: undefined,
};

function normalizeLang(lang) {
  const l = (lang ?? "en").toLowerCase().slice(0, 2);
  if (l in DICTS) return l;
  return "en";
}

/**
 * Translate a static UI key. Falls back to the English entry if the language
 * has no translation table, or to the key itself if even English is missing
 * (which would be a bug worth surfacing).
 */
export function t(key, lang) {
  const dict = DICTS[normalizeLang(lang)] ?? EN;
  return dict[key] ?? EN[key] ?? key;
}

export function isDevanagariScript(lang) {
  const l = normalizeLang(lang);
  return l === "hi" || l === "mr";
}
