#!/usr/bin/env node
/**
 * Build the learn pages from the report engine.
 *
 * Every sentence on /learn/* comes out of the code that generates a paying
 * customer's report — engine/lib/dosha-details.js (English),
 * engine/i18n/dosha-details-hi.js (Hindi), engine/mapping/dosh-i18n.js (the
 * formation rules) and engine/astrology/detect-doshas.js (the cancellation
 * clauses and the severity scale).
 *
 * That is the whole point. The alternative — writing a few dozen astrology
 * articles, or worse generating them — produces content that is unverifiable,
 * indistinguishable from every other astrology blog, and liable to contradict
 * the reports we actually sell. Deriving them means the site can only say what
 * the engine says, in both languages, and a change to a remedy in the engine
 * shows up on the website on the next build.
 *
 * Output: src/content/doshas.generated.ts — committed, so a build does not
 * depend on pothi-api being present, but regenerated by prebuild when it is.
 *
 *   node scripts/build_content.js [--check]
 *     --check  regenerate into memory and diff against the committed file;
 *              exit 1 if they differ. Used by CI so the two cannot drift.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DOSHA_PAGES, RULE_KEY, SEVERITY_BANDS } from "./content/dosha-index.js";
import { MANGLIK_CLAUSES } from "./content/manglik-clauses.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const API = resolve(ROOT, "../pothi-api");
const OUT = join(ROOT, "src/content/doshas.generated.ts");
const CHECK = process.argv.includes("--check");

const deva = (s) => /[ऀ-ॿ]/.test(String(s || ""));

async function engine() {
  if (!existsSync(API)) throw new Error(`pothi-api not found at ${API}`);
  const [en, hi, i18n] = await Promise.all([
    import(join(API, "engine/lib/dosha-details.js")),
    import(join(API, "engine/i18n/dosha-details-hi.js")),
    import(join(API, "engine/mapping/dosh-i18n.js"))
  ]);
  return { EN: en.DOSHA_DETAILS, HI: hi.DOSHA_DETAILS_HI, FORMATION: i18n.FORMATION_RULE, AFFECTS: i18n.AFFECTS };
}

/**
 * The questions people type, answered from fields that already exist.
 *
 * Templated rather than written, so an answer can only ever restate something
 * the engine already says. The cost is that they read a little uniform; the
 * benefit is that none of them can be wrong in a way the reports are not.
 */
function faqs(lang, page, d, rule) {
  const name = d.name;
  const remedyTitles = (d.remedies || []).slice(0, 3).map((r) => r.title);
  const out = [];

  if (rule) {
    out.push(lang === "hi"
      ? { q: `${name} कैसे बनता है?`, a: rule }
      : { q: `How does ${name} form?`, a: rule });
  }

  out.push(lang === "hi"
    ? { q: `क्या मेरी कुंडली में ${name} है?`,
        a: `यह केवल आपकी जन्म कुंडली से ही तय हो सकता है — जन्म तिथि, सटीक समय और स्थान से। ${d.whenPresent}` }
    : { q: `Do I have ${name}?`,
        a: `Only your own birth chart can answer that — it needs your date, exact time and place of birth. ${d.whenPresent}` });

  if (d.whenAbsent) {
    out.push(lang === "hi"
      ? { q: `यदि ${name} न हो तो?`, a: d.whenAbsent }
      : { q: `What if ${name} is not present?`, a: d.whenAbsent });
  }

  if (remedyTitles.length) {
    out.push(lang === "hi"
      ? { q: `${name} के उपाय क्या हैं?`,
          a: `शास्त्रोक्त उपायों में ${remedyTitles.join(", ")} सम्मिलित हैं। कोई भी रत्न धारण करने से पूर्व योग्य ज्योतिषी से परामर्श अवश्य करें।` }
      : { q: `What are the remedies for ${name}?`,
          a: `The classical remedies include ${remedyTitles.join(", ")}. Consult a qualified astrologer before wearing any gemstone.` });
  }

  if (d.ruler) {
    out.push(lang === "hi"
      ? { q: `${name} का कारक ग्रह कौन है?`, a: `${d.ruler}। ${d.significance}` }
      : { q: `Which planet causes ${name}?`, a: `${d.ruler}. ${d.significance}` });
  }

  if (page.key === "manglik") {
    const full = MANGLIK_CLAUSES.filter((c) => c.weight === "full").length;
    const part = MANGLIK_CLAUSES.filter((c) => c.weight === "partial").length;
    out.push(lang === "hi"
      ? { q: "क्या मांगलिक दोष निरस्त हो सकता है?",
          a: `हाँ। शास्त्र ${full} पूर्ण निवारण और ${part} आंशिक निवारण स्वीकार करते हैं — जैसे मंगल का स्वराशि या उच्च राशि में होना, अथवा गुरु की दृष्टि। अधिकांश स्थानों पर ये खंड बताए ही नहीं जाते, इसीलिए दोष वास्तविकता से कहीं अधिक भयावह लगता है।` }
      : { q: "Can Manglik dosha be cancelled?",
          a: `Yes. The texts accept ${full} full cancellations and ${part} partial ones — Mars in his own or exaltation sign, Jupiter's aspect, and others. Most sources never mention these clauses, which is why the dosha reads as far more alarming than it is.` });
  }

  return out;
}

function article(lang, page, src) {
  const d = src[lang === "hi" ? "HI" : "EN"][page.key];
  if (!d) throw new Error(`${page.key}: no ${lang} details in the engine`);
  const ruleKey = RULE_KEY[page.key];
  const rule = ruleKey ? src.FORMATION[ruleKey]?.[lang] || null : null;
  const affects = ruleKey ? src.AFFECTS[ruleKey]?.[lang] || null : null;

  // A Hindi page carrying English body text is worse than no Hindi page: it
  // reads as machine output and it competes with our own English URL.
  if (lang === "hi") {
    for (const [f, v] of Object.entries({ intro: d.intro, significance: d.significance, whenPresent: d.whenPresent })) {
      if (v && !deva(v)) throw new Error(`${page.key}: Hindi ${f} is not in Devanagari — untranslated`);
    }
  }

  return {
    key: page.key,
    slug: page.slug,
    lang,
    title: page[lang].title,
    blurb: page[lang].blurb,
    name: d.name,
    ruler: d.ruler,
    affects,
    rule,
    intro: d.intro,
    significance: d.significance,
    whenPresent: d.whenPresent,
    whenAbsent: d.whenAbsent,
    effects: d.effects || [],
    remedies: d.remedies || [],
    lucky: d.lucky || null,
    clauses: page.key === "manglik" ? MANGLIK_CLAUSES.map((c) => ({ weight: c.weight, ...c[lang] })) : [],
    faqs: faqs(lang, page, d, rule),
    severity: SEVERITY_BANDS.map((b) => ({ min: b.min, label: b[lang] }))
  };
}

const src = await engine();
const articles = [];
for (const page of DOSHA_PAGES) {
  for (const lang of ["en", "hi"]) articles.push(article(lang, page, src));
}

// Sanity: a page too thin to be worth publishing is a page that should not be
// published. 900 characters of body is not a long read, but it is well past the
// point where a page is just a stub with a buy button on it.
const thin = articles.filter((a) => {
  const n = [a.intro, a.significance, a.whenPresent, a.whenAbsent, ...a.effects,
             ...a.remedies.map((r) => `${r.title} ${r.detail}`),
             ...a.clauses.map((c) => `${c.label} ${c.detail}`),
             ...a.faqs.map((f) => `${f.q} ${f.a}`)].join(" ").length;
  return n < 900;
});
if (thin.length) {
  console.error(`  ✗ ${thin.length} article(s) below the length floor: ${thin.map((a) => `${a.slug}/${a.lang}`).join(", ")}`);
  process.exit(1);
}

const body = `// GENERATED by scripts/build_content.js — do not edit.
//
// Derived from the report engine: engine/lib/dosha-details.js,
// engine/i18n/dosha-details-hi.js, engine/mapping/dosh-i18n.js and
// engine/astrology/detect-doshas.js. To change what a learn page says, change
// the engine and re-run \`npm run content\` — editing this file by hand will be
// overwritten and will make the site disagree with the reports.

export type Remedy = { title: string; detail: string };
export type Clause = { weight: "full" | "partial" | "mitigator"; label: string; detail: string };
export type Faq = { q: string; a: string };
export type Lucky = {
  color?: string; day?: string; number?: number; gemstone?: string;
  metal?: string; direction?: string; deity?: string; mantra?: string;
};
export type Article = {
  key: string; slug: string; lang: "en" | "hi";
  title: string; blurb: string; name: string; ruler: string;
  affects: string | null; rule: string | null;
  intro: string; significance: string; whenPresent: string; whenAbsent: string;
  effects: string[]; remedies: Remedy[]; lucky: Lucky | null;
  clauses: Clause[]; faqs: Faq[];
  severity: { min: number; label: string }[];
};

export const ARTICLES: Article[] = ${JSON.stringify(articles, null, 2)};

/** Slug order for the index pages — the order in scripts/content/dosha-index.js. */
export const SLUGS: string[] = ${JSON.stringify(DOSHA_PAGES.map((p) => p.slug), null, 2)};

export const findArticle = (slug: string, lang: "en" | "hi"): Article | undefined =>
  ARTICLES.find((a) => a.slug === slug && a.lang === lang);

export const articlesIn = (lang: "en" | "hi"): Article[] =>
  SLUGS.map((s) => findArticle(s, lang)).filter(Boolean) as Article[];
`;

if (CHECK) {
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (have !== body) {
    console.error("  ✗ src/content/doshas.generated.ts is stale — run `npm run content`");
    process.exit(1);
  }
  console.log(`  ✓ content up to date — ${articles.length} articles`);
} else {
  writeFileSync(OUT, body);
  const words = articles.reduce((n, a) =>
    n + [a.intro, a.significance, a.whenPresent, a.whenAbsent, ...a.effects,
         ...a.remedies.map((r) => `${r.title} ${r.detail}`),
         ...a.clauses.map((c) => `${c.label} ${c.detail}`),
         ...a.faqs.map((f) => `${f.q} ${f.a}`)].join(" ").split(/\s+/).length, 0);
  console.log(`  ✓ ${articles.length} articles (${DOSHA_PAGES.length} × en/hi), ~${Math.round(words / articles.length)} words each`);
}
