#!/usr/bin/env node
/**
 * Encode the pitch video for autoplay on a phone.
 *
 * The source is a 2.4MB 720×1280 h264 clip. Autoplaying that on mobile data is
 * a real cost to a visitor who never asked for it, so it is re-encoded twice —
 * WebM/VP9 for browsers that take it, MP4/h264 for Safari — and a poster frame
 * is pulled so the box is filled before a single byte of video is fetched.
 *
 * The audio track is kept: the video autoplays muted (browsers require it, and
 * sound that starts on its own is hostile), but the point of the clip is
 * somebody talking, so unmuting has to be one tap away.
 *
 *   npm run video
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "../ads/assets/Man_speaking_to_camera_202608211725.mp4");
const OUT = join(ROOT, "public/video");

if (!existsSync(SRC)) { console.error(`  ✗ source not found: ${SRC}`); process.exit(1); }
mkdirSync(OUT, { recursive: true });

const kb = (p) => Math.round(statSync(p).size / 1024);
const run = (args) => execFileSync("ffmpeg", ["-y", "-loglevel", "error", ...args]);

const probe = execFileSync("ffprobe", ["-v", "error", "-select_streams", "v:0",
  "-show_entries", "stream=width,height,duration", "-of", "csv=p=0", SRC], { encoding: "utf8" }).trim();
const [width, height, duration] = probe.split(",");

// Poster: a frame from one second in, not zero — the first frame of a talking
// clip is usually a half-blink.
run(["-ss", "1", "-i", SRC, "-frames:v", "1", "-q:v", "3", join(OUT, "pitch-poster.jpg")]);

// h264: crf 28 is where a talking head at this size stops losing anything you
// can see. faststart puts the index first so playback can begin while it loads.
run(["-i", SRC, "-c:v", "libx264", "-crf", "31", "-preset", "slow", "-profile:v", "main",
     "-pix_fmt", "yuv420p", "-movflags", "+faststart",
     "-c:a", "aac", "-b:a", "64k", "-ac", "1", join(OUT, "pitch.mp4")]);

// VP9. At crf 36 this came out LARGER than the h264 — VP9's quality scale is
// not h264's, and a number copied across from one to the other is how that
// happens. 42 is the equivalent point for this clip.
run(["-i", SRC, "-c:v", "libvpx-vp9", "-crf", "42", "-b:v", "0", "-row-mt", "1",
     "-c:a", "libopus", "-b:a", "48k", "-ac", "1", join(OUT, "pitch.webm")]);

writeFileSync(join(ROOT, "src/content/video.generated.ts"),
`// GENERATED by scripts/build_video.js — do not edit. Run \`npm run video\`.
export const PITCH_VIDEO = {
  mp4: "/video/pitch.mp4",
  webm: "/video/pitch.webm",
  poster: "/video/pitch-poster.jpg",
  width: ${width},
  height: ${height},
  seconds: ${Math.round(Number(duration))}
};
`);

console.log(`  source      ${width}×${height} ${Math.round(Number(duration))}s  ${kb(SRC)}KB`);
console.log(`  pitch.mp4   ${kb(join(OUT, "pitch.mp4"))}KB`);
console.log(`  pitch.webm  ${kb(join(OUT, "pitch.webm"))}KB`);
console.log(`  poster      ${kb(join(OUT, "pitch-poster.jpg"))}KB`);
