#!/usr/bin/env node
/**
 * Optimise the promo banners for the dosh report page — language-aware.
 *
 * Source images live in ads/assets, prefixed by language: `hi_*` are the Hindi
 * banners, `en_*` the English ones. Each is a 1376×768 JPEG from the ad tooling.
 * Served as-is to a phone rendering them ~390px wide, that is four times the
 * pixels anyone sees, on the one screen an ad campaign pays to put people on.
 *
 * So each is emitted as WebP at two widths and picked with srcset. The manifest
 * records the language, so the component shows the Hindi set to a Hindi reader
 * and the English set to an English one, and reserves the box before the bytes
 * arrive (no reflow, no Core Web Vitals penalty).
 *
 * Glob-based on purpose: the filenames carry timestamps and a unicode ellipsis,
 * so hard-coding them is fragile. Drop new hi_/en_ images in and re-run.
 *
 *   npm run banners
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, statSync, readdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "../ads/assets");
const OUT = join(ROOT, "public/banners");
const WIDTHS = [800, 1376];

if (!existsSync(SRC)) { console.error(`  ✗ source images not found at ${SRC}`); process.exit(1); }
mkdirSync(OUT, { recursive: true });

// A stable id from the filename: language prefix + first two descriptive words,
// so the same picture keeps the same slug across re-runs.
const slug = (file) =>
  file.replace(/\.(jpe?g|png)$/i, "")
      .replace(/_\d{10,}$/, "")            // drop the timestamp tail
      .replace(/[….]+$/, "")              // drop trailing ellipsis
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .split("-").slice(0, 5).join("-");

const kb = (p) => Math.round(statSync(p).size / 1024);
const manifest = { hi: [], en: [] };
let before = 0, after = 0;

for (const lang of ["hi", "en"]) {
  const files = readdirSync(SRC).filter((f) => f.startsWith(`${lang}_`) && /\.(jpe?g|png)$/i.test(f)).sort();
  if (!files.length) { console.error(`  ✗ no ${lang}_ banners found in ${SRC}`); process.exit(1); }

  for (const file of files) {
    const src = join(SRC, file);
    before += kb(src);
    const id = slug(file);

    const [w, h] = execFileSync("sips", ["-g", "pixelWidth", "-g", "pixelHeight", src], { encoding: "utf8" })
      .match(/\d+/g).slice(-2).map(Number);

    const out = {};
    for (const width of WIDTHS) {
      const name = `${id}-${width}.webp`;
      const dst = join(OUT, name);
      execFileSync("cwebp", ["-q", "78", "-m", "6", "-resize", String(width), "0", src, "-o", dst], { stdio: "ignore" });
      out[width] = `/banners/${name}`;
      after += kb(dst);
    }
    // alt is descriptive, from the filename — the picture, not a second ad slot.
    const alt = file.replace(/^(hi|en)_/, "").replace(/_\d{10,}.*$/, "").replace(/[_…]+/g, " ").trim();
    manifest[lang].push({ id, alt: `astropothi — ${alt}`, width: w, height: h, files: out });
    console.log(`  ${lang}  ${id.padEnd(28)} ${w}×${h}`);
  }
}

writeFileSync(join(ROOT, "src/content/banners.generated.ts"),
`// GENERATED by scripts/build_banners.js — do not edit.
// Run \`npm run banners\` after changing the source images in ads/assets.
export type Banner = {
  id: string; alt: string; width: number; height: number;
  files: Record<string, string>;
};
// Keyed by language: the Hindi reader sees the hi_ set, the English reader the en_ set.
export const BANNERS: Record<"hi" | "en", Banner[]> = ${JSON.stringify(manifest, null, 2)};
`);

console.log(`  ✓ ${manifest.hi.length} hi + ${manifest.en.length} en banners — ${before}KB → ${after}KB`);
