export const pageMap = [
  { page: 1,  id: "cover",                 title: "Cosmic Identity",                   subtitle: "Premium Vedic Birth Report" },
  { page: 2,  id: "basic-details",         title: "Basic Astrological Details" },
  { page: 3,  id: "planetary-positions",   title: "Planetary Positions" },
  { page: 4,  id: "horoscope-charts",      title: "Horoscope Charts" },
  { page: 5,  id: "divisional-charts",     title: "Divisional Charts" },
  { page: 6,  id: "house-cusps",           title: "House Cusps and Sandhi" },
  { page: 7,  id: "vimshottari-dasha-1",   title: "Vimshottari Dasha - I" },
  { page: 8,  id: "vimshottari-dasha-2",   title: "Vimshottari Dasha - II" },
  { page: 9,  id: "favourable-points",     title: "Favourable Points" },
  { page: 10, id: "numerology-report",     title: "Numerology Report" },
  { page: 11, id: "gayatri-mantra",        title: "Favourable Gayatri Mantra For You" },
  { page: 12, id: "kalsarpa-dosha",        title: "Kalsarpa Dosha" },
  { page: 13, id: "kalsarpa-dosha-effect", title: "Kalsarpa Dosha Effect" },
  { page: 14, id: "manglik-analysis-1",    title: "Manglik Analysis - I" },
  { page: 15, id: "manglik-analysis-2",    title: "Manglik Analysis - II" },
  { page: 16, id: "sadhesati-analysis",    title: "Sadhesati Analysis" },
  { page: 17, id: "dosha-summary",         title: "Dosha Summary" },
  { page: 18, id: "ashtakavarga",          title: "Ashtakavarga" },
  { page: 19, id: "gemstone-suggestions",  title: "Gemstone Suggestions" },
  { page: 20, id: "life-stone",            title: "Life Stone" },
  { page: 21, id: "benefic-stone",         title: "Benefic Stone" },
  { page: 22, id: "lucky-stone",           title: "Lucky Stone" },
  { page: 23, id: "ascendant-report-1",    title: "Ascendant Report" },
  { page: 24, id: "ascendant-report-2",    title: "Ascendant Detailed" },
  { page: 25, id: "final",                 title: "Thank You" }
];
